In [1]:
import pandas as pd
import numpy as np
import geopandas as gpd
from matplotlib import pyplot as plt

df_releases = pd.read_csv('../data/releases.csv')
df_releases.head()

        id    country        date        type rating
0  1000001    Andorra  2023-07-21  Theatrical    NaN
1  1000001  Argentina  2023-07-20  Theatrical    ATP
2  1000001  Australia  2023-07-19  Theatrical     PG
3  1000001  Australia  2023-10-01     Digital     PG
4  1000001    Austria  2023-07-20  Theatrical    NaN

In [2]:
df_releases.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1332782 entries, 0 to 1332781
Data columns (total 5 columns):
 #   Column   Non-Null Count    Dtype
---  ------   --------------    -----
 0   id       1332782 non-null  int64
 1   country  1332782 non-null  object
 2   date     1332782 non-null  object
 3   type     1332782 non-null  object
 4   rating   333980 non-null   object
dtypes: int64(1), object(4)
memory usage: 50.8+ MB

In [3]:
df_releases.describe()

                 id
count  1.332782e+06
mean   1.308420e+06
std    2.879215e+05
min    1.000001e+06
25%    1.030644e+06
50%    1.231844e+06
75%    1.543296e+06
max    1.940971e+06

In [4]:
df_releases.dtypes

id          int64
country    object
date       object
type       object
rating     object
dtype: object

In [ ]:
df_releases.loc[]