In [41]:
import pandas as pd
import numpy as np
import geopandas as gpd
from matplotlib import pyplot as plt

df_studios = pd.read_csv('../data/studios.csv')
df_studios.head()

        id                   studio
0  1000001  LuckyChap Entertainment
1  1000001             Heyday Films
2  1000001           NB/GG Pictures
3  1000001                   Mattel
4  1000001    Warner Bros. Pictures

In [42]:
df_studios.sample(5)

             id                        studio
609398  1737014                         Astro
368169  1287597        Rich Animation Studios
599975  1713870     شركة الوسام للإنتاج الفني
242494  1143433  Multicom Entertainment Group
382688  1308140                Yucca Pictures

In [43]:
df_studios.rename(columns={'id': 'film'}, inplace=True)
df_studios.head()

      film                   studio
0  1000001  LuckyChap Entertainment
1  1000001             Heyday Films
2  1000001           NB/GG Pictures
3  1000001                   Mattel
4  1000001    Warner Bros. Pictures

In [44]:
df_studios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 679283 entries, 0 to 679282
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   film    679283 non-null  int64
 1   studio  679273 non-null  object
dtypes: int64(1), object(1)
memory usage: 10.4+ MB

In [45]:
df_studios.describe()

               film
count  6.792830e+05
mean   1.319075e+06
std    2.660925e+05
min    1.000001e+06
25%    1.083656e+06
50%    1.249924e+06
75%    1.516158e+06
max    1.941596e+06

In [46]:
df_studios.dtypes

film       int64
studio    object
dtype: object

In [47]:
df_studios['studio'].value_counts()

studio
BBC                       3560
Warner Bros. Pictures     3222
Columbia Pictures         3000
ARTE                      2824
Metro-Goldwyn-Mayer       2789
                          ...
Vivo Siendo Cine             1
Kanka Productions            1
Dioni Visions                1
As It Happens Creative       1
亚太国影（重庆）文化传媒有限公司             1
Name: count, Length: 160881, dtype: int64