In [2]:
import pandas as pd
import numpy as np
import geopandas as gpd
import seaborn as sns
from matplotlib import pyplot as plt

df_themes = pd.read_csv('../data/themes.csv')
df_themes.head()

        id                                              theme
0  1000001                   Humanity and the world around us
1  1000001                             Crude humor and satire
2  1000001                        Moving relationship stories
3  1000001     Emotional and captivating fantasy storytelling
4  1000001  Surreal and thought-provoking visions of life ...

In [3]:
df_themes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125641 entries, 0 to 125640
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   id      125641 non-null  int64
 1   theme   125641 non-null  object
dtypes: int64(1), object(1)
memory usage: 1.9+ MB

In [4]:
df_themes.describe()

                 id
count  1.256410e+05
mean   1.023455e+06
std    3.865890e+04
min    1.000001e+06
25%    1.005213e+06
50%    1.013261e+06
75%    1.028295e+06
max    1.849827e+06

In [12]:
df_themes['theme'].value_counts()

theme
Moving relationship stories                   4012
Crude humor and satire                        3816
Horror, the undead and monster classics       3742
Twisted dark psychological thriller           3315
Gory, gruesome, and slasher horror            3132
                                              ...
Captivating vision and Shakespearean drama     277
Air pilot heroism and survival                 216
Underdog fighting and boxing stories           183
Teen friendship and coming-of-age               92
Engaging, intense crime and casino drama        68
Name: count, Length: 109, dtype: int64

In [28]:
df_themes['theme'].isna().sum()

np.int64(0)